export const ACTION_TYPES = {
    INVITE_USER: "INVITE_USER",
    CREATE_USER: "CREATE_USER",
    UPDATE_USER: "UPDATE_USER",
    DELETE_USER: "DELETE_USER",
    CREATE_PROFILE: "CREATE_PROFILE",
    UPDATE_PROFILE: "UPDATE_PROFILE",
    DELETE_PROFILE: "DELETE_PROFILE",
    CREATE_VENUE: "CREATE_VENUE",
    UPDATE_VENUE: "UPDATE_VENUE",
    DELETE_VENUE: "DELETE_VENUE",
    CREATE_COURT: "CREATE_COURT",
    UPDATE_COURT: "UPDATE_COURT",
    DELETE_COURT: "DELETE_COURT",
    CREATE_BOOKING: "CREATE_BOOKING",
    UPDATE_BOOKING: "UPDATE_BOOKING",
    DELETE_BOOKING: "DELETE_BOOKING",
    // Order actions
    CREATE_ORDER: "CREATE_ORDER",
    UPDATE_ORDER: "UPDATE_ORDER",
    CANCEL_ORDER: "CANCEL_ORDER",
    // Payment actions
    UPDATE_PAYMENT: "UPDATE_PAYMENT",
    // RBAC actions
    CREATE_ROLE: "CREATE_ROLE",
    UPDATE_ROLE: "UPDATE_ROLE",
    DELETE_ROLE: "DELETE_ROLE",
    UPDATE_ROLE_PERMISSION: "UPDATE_ROLE_PERMISSION",
    // Dynamic pricing actions
    CREATE_DYNAMIC_PRICE: "CREATE_DYNAMIC_PRICE",
    UPDATE_DYNAMIC_PRICE: "UPDATE_DYNAMIC_PRICE",
    DELETE_DYNAMIC_PRICE: "DELETE_DYNAMIC_PRICE",
    // Manual booking action
    CREATE_MANUAL_BOOKING: "CREATE_MANUAL_BOOKING",
}

export type ActionType = typeof ACTION_TYPES[keyof typeof ACTION_TYPES];